---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:mrdummydoofy/gitops-helm
    path: charts/podinfo
    ref: master
  values:
    image: mrdummydoofy/podinfo:dev-99lwjoos
    replicaCount: 1
    hpa:
      enabled: false
    resources:
      limits:
      requests:
        cpu: 11m
        memory: 16Mi
